### ISSUE TITLE
Texte présentation du site

### ISSUE THREAD

**Issue by karinedeker** [nicolasdeker/babyromandie#12]
A la naissance de mon premier enfant, j’ai commencé à chercher des activités à faire avec un bébé. J’accumulais les infos sur mon ordi et je stockais les flyers dans mon sac et mes tiroirs. J’ai voulu d’abord tout rassembler dans un tableau. Mais voyant la difficulté pour dénicher  toutes les adresses sur internet j’ai décidé de partager mes recherches sur un site internet. Et faire ainsi gagner du temps aux parents en facilitant leur recherche par critère. 

Baby Romandie est un site 100% gratuit pour les famille en Suisse Romande rassemblant toutes les informations utiles à découvrir sur un seul et même site. Les idées de sorties dans toute la romandie et en France voisine, les cours pour femmes enceintes, pour bébé et pour enfant jusqu'à  12 ans. Mais aussi des adresses pour réussir un anniversaire, se détendre ou faire du shopping pour nos enfants. Quant à la rubrique partage de bons plans j’invite les familles à échanger leurs infos sur différents sujets comme les recettes, les promos du moment, l’agenda des activités ponctuelles, les modes de garde, les avis sur des produits…

N'hésiter à m'aider à faire vivre Babyromandie en partageant votre expérience, vos astuces, vos bons plans… dans cette aventure de parents.

**Comment by nicolasdeker** [comment]
A la naissance de mon premier enfant, j’ai commencé à chercher des activités à faire avec lui. J’accumulais des informations dans mes mails, stockais des flyers dans mon sac etc. J'ai remarqué que ces recherches me prenaient beacoup de temps et qu'aucun site ne regroupait toutes ces informations dont j'avais besoin. 

J’ai ainsi décidé de partager le fruit de mes recherches afin de faire gagner du temps aux autres parents.

Baby Romandie est un site 100% gratuit pour les famille en Suisse Romande, qui rassemble toutes les informations utiles sur un seul et même site : 
les sorties familiales en Romandie et en France voisine, les cours pour femmes enceintes, pour bébé ; Mais aussi des adresses pour réussir un anniversaire, se détendre ou faire du shopping pour nos enfants. Quant à la rubrique partage de bons plans j’invite les familles à échanger leurs infos sur différents sujets comme les recettes, les promos du moment, l’agenda des activités ponctuelles, les modes de garde, les avis sur des produits…

N'hésiter à m'aider à faire vivre Babyromandie en partageant votre expérience, vos astuces, vos bons plans… dans cette aventure de parents.

**Comment by nicolasdeker** [comment]
A la naissance de mon premier enfant, j’ai commencé à chercher des activités à faire avec lui. J’accumulais des informations dans mes mails, stockais des flyers dans mon sac etc. J'ai remarqué que ces recherches me prenaient beacoup de temps et qu'aucun site ne regroupait toutes ces informations dont j'avais besoin.

J’ai ainsi décidé de partager le fruit de mes recherches afin de faire gagner du temps aux autres parents.

Baby Romandie est un site 100% gratuit pour les famille en Suisse Romande, qui rassemble toutes les informations utiles sur un seul et même site :
les sorties familiales en Romandie et en France voisine, les cours pour femmes enceintes, pour bébé ; Mais aussi des adresses pour réussir un anniversaire, se détendre ou faire du shopping pour nos enfants. Quant à la rubrique partage de bons plans j’invite les familles à échanger leurs infos sur différents sujets comme les recettes, les promos du moment, l’agenda des activités ponctuelles, les modes de garde, les avis sur des produits…

Aidez moi à faire vivre Babyromandie en partageant vos expérience, vos astuces, vos bons plans…
