### ISSUE TITLE
Insérer un mail spécifique pour l'annonce d'un cours, sortie....

### ISSUE THREAD

**Issue by karinedeker** [nicolasdeker/babyromandie#4]
Dans les pages : sorties, cours, shopping, halte-jeux, anniversaire et massages donnez la possibilités au gens d'envoyer un mail pour faire connaître un cours, une sortie...
Il faut qu'il puisse (sans obligation ) mettre tous ces champs:
-nom
-texte
-horaire
-jour
-adresse
-ville
-pays
-numéro
-mail
-site internet
Et une photo

**Comment by nicolasdeker** [comment]
j'ai ajouté un formulaire en bas de toutes les pages, c'est déjà pas mal non?
